### ISSUE TITLE
wasm-rust example crashes

### ISSUE THREAD

**Issue by muratcorlu** [stackpath/serverless-scripting-examples#31]
**Describe the bug**  
I'm trying to run [wasm-rust](https://github.com/stackpath/serverless-scripting-examples/tree/master/wasm-rust). It works on my local but crashes on stackpath. When I debug it on your serverless sandbox, I saw error message below.

```
[error] Error: An object was thrown from supplied code within isolated-vm, but that object was not an instance of `Error`.
    at Object.dispatchSync (dist/v8env.js:15:53154)
    at t.TextDecoder.decode (dist/v8env.js:23:59534)
    at Module.<anonymous> (<script>:1:3840)
    at Module.<anonymous> (<script>:1:8353)
    at t (<script>:1:110)
    at Module.<anonymous> (<script>:1:781753)
    at t (<script>:1:110)
    at <script>:1:902
    at <script>:1:911
```

**To reproduce**  
I didn't make any change. Just build and deploy it. Or try it in [serverless sandbox](https://sandbox.edgeengine.io/)

**Expected behavior**  
On my local it returns resized image. I was expecting same on stackpath.

**Actual behavior**  
Instead I'm getting server error.

**Comment by klaude** [comment]
Thanks for the issue, @muratcorlu. I'll build and deploy our Rust example and see if I can duplicate this. I'll let you know what I see!

**Comment by klaude** [comment]
Sure enough I'm seeing the same thing. You're doing it right, and this doesn't look like a problem with the Rust example. This looks like it's something on our side.

It looks like you've already got a support issue open for this. I've raised a flag with our backend serverless engineering folks to look into this. Stay tuned to that support issue for updates as we have them. If there's nothing else I can do for you today then I'll close this issue out. Thanks much!
